version: '3'
services:
  mysql-db:
#    container_name: mysql-db
    image: mysql/mysql-server
    environment:
      MYSQL_DATABASE: psheldon
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-db:/var/lib/mysql
  instance_1:
    image: "leader-selection-demo:0.0.1-SNAPSHOT"
    environment:
      - INSTANCE_ID=1
      - DB_HOST=mysql-db
    ports:
      - "8080:8080"
  instance_2:
    image: "leader-selection-demo:0.0.1-SNAPSHOT"
    environment:
      - INSTANCE_ID=2
      - DB_HOST=mysql-db
    ports:
      - "8082:8080"
  instance_3:
    image: "leader-selection-demo:0.0.1-SNAPSHOT"
    environment:
      - INSTANCE_ID=3
      - DB_HOST=mysql-db
    ports:
      - "8083:8080"