mysql-options: '?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC'
spring:
  application:
    name: leader_selection
leaderSelection:
  instanceId: insta-id
  fixedDelay: 5000
  initialDelay:  5000
  heartBeatThreshold: 30000

someOtherProcessor:
  fixedDelay: 2000
  initialDelay:  5000
