spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/leader_selection${mysql-options}
    username: psheldon
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/leader_selection${mysql-options}
    user: psheldon
    password: password
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    ROOT: WARN
    com.pksheldon4.sample.leaderselection: DEBUG